### ISSUE TITLE
v0.8.5 Error: Cannot find module '../util.js'

### ISSUE THREAD

**Issue by kolegm** [derbyparty/generator-derby#31]
Could not create a new project using version generator-derby@0.8.5
```bash
$ yo derby project-name
Error: Cannot find module '../util.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-derby/app/index.js:6:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by zag2art** [comment]
Wierd. Actually I don't know the reason. But anyway I fixed `package.json` to include absolutely all module files into `npm`. Please, try 0.8.6 and give me a feedback.

**Comment by kolegm** [comment]
Please, update project version on npmjs.com

Thanks

2015-03-03 16:01 GMT+02:00 Artur Zayats <notifications@github.com>:

**Comment by zag2art** [comment]
Done

**Comment by kolegm** [comment]
Tested
