### ISSUE TITLE
Generator Fails 

### ISSUE THREAD

**Issue by daslicht** [derbyparty/generator-derby#34]
I I get the following error:
```
daslicht:simple daslicht$ yo derby

Derby 0.6 Project generator:

? Select Project level features Redis
? Input Derby-app name simple
? Select "simple"-application features derby-router, Bootstrap 3
   create config/defaults.json
   create public/img/favicon.ico
   create server/error.js
   create server/routes.js
   create server/config.js
   create server/express.js
   create server/store.js
   create server.js
   create package.json
   create .gitignore
   create README.md
   create apps/error/index.js
   create apps/error/views/index.html
   create apps/error/views/403.html
   create apps/error/views/404.html
   create apps/error/views/500.html
   create apps/error/styles/index.css
   create apps/error/styles/reset.css
   create apps/simple/index.js
   create apps/simple/views/index.html
   create apps/simple/views/home.html
   create apps/simple/styles/index.css


I'm all done. Running npm install

npm WARN package.json simple@0.0.0 No repository field.
npm WARN package.json simple@0.0.0 No license field.
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "derby@0.6.0" "sharedb-mongo" "racer-bundle" "racer-highway" "coffeeify" "coffee-script" "async" "chalk" "express" "connect-mongo" "cookie-parser" "body-parser" "express-session" "serve-static" "compression" "serve-favicon" "redis-url" "sharedb-redis-pubsub" "derby-debug" "d-bootstrap" "derby-router" "--save"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7

npm ERR! version not found: derby@0.6.0
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/daslicht/DEV/node/derby/simple/npm-debug.log

All is done, to start app use: npm start

daslicht:simple daslicht$ npm install
npm WARN package.json simple@0.0.0 No repository field.
npm WARN package.json simple@0.0.0 No license field.
daslicht:simple daslicht$ ls
README.md	components	package.json	server		test
apps		config		public		server.js
daslicht:simple daslicht$ npm install
npm WARN package.json simple@0.0.0 No repository field.
npm WARN package.json simple@0.0.0 No license field.
daslicht:simple daslicht$ npm start

> simple@0.0.0 start /Users/daslicht/DEV/node/derby/simple
> node server.js

module.js:339
    throw err;
    ^

Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/daslicht/DEV/node/derby/simple/server.js:1:75)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! simple@0.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the simple@0.0.0 start script 'node server.js'.
npm ERR! This is most likely a problem with the simple package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls simple
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/daslicht/DEV/node/derby/simple/npm-debug.log
daslicht:simple daslicht$ 

```

**Comment by zag2art** [comment]
Something wrong with npm itself. Enter `npm view derby`. Sometimes it show derby@0.6.0, sometimes no. Don't know what can I do.

**Comment by zag2art** [comment]
Plaese downgrade node to 0.12 and npm to 2.7.5

**Comment by daslicht** [comment]
I tried that , now I get another error that yo needs a newer version lol
