### ISSUE TITLE
derby-login needs some update

### ISSUE THREAD

**Issue by droganov** [derbyparty/generator-derby#40]
```

Master pid  29227
/www/tmp/derby/node_modules/derby-login/lib/middleware/index.js:40
  backend.addProjection(options.publicCollection, options.collection, 'json0', options.user);
         ^

TypeError: Cannot read property 'addProjection' of undefined
  at Login.middleware (/www/tmp/derby/node_modules/derby-login/lib/middleware/index.js:40:10)
  at module.exports (/www/tmp/derby/server/express.js:36:21)
  at /www/tmp/derby/server.js:24:3
  at Racer.Derby.run (/www/tmp/derby/node_modules/derby/lib/Derby.server.js:17:5)
  at Object.<anonymous> (/www/tmp/derby/server.js:9:7)
  at Module._compile (module.js:434:26)
  at Object.Module._extensions..js (module.js:452:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:475:10)
  at startup (node.js:118:18)
  at node.js:952:3

```

**Comment by zag2art** [comment]
Create an issue in derby-login itself please
